projects/myboard/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:id>/', views.read, name = 'detail'),
    
    path('write/', views.write, name = 'write'),

    path('<int:id>/update/', views.update, name = 'update'),

    path('<int:id>/delete/', views.delete, name = 'delete'),

    path('<int:id>/write_reply/', views.write_reply, name= 'write_reply'),

    #댓글삭제주소
    path('<int:id>/delete_reply/<int:rid>/', views.delete_reply, name= 'delete_reply'),

    path('<int:id>/update_reply/', views.update_reply, name = 'update_reply'),

    #Ajax
    path('callAjax/', views.call_ajax),

    path('load_reply/', views.load_reply),
]

projects/myboard/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
#현재 폴더에서 views를 가지고 오는데 그 이름이,,,
from . import views as common_views

app_name = 'common'

urlpatterns = [
    path('', common_views.index, name = 'index'),
    path('login/', auth_view.LoginView.as_view(template_name = 'common/login.html'),name = 'login'),
    path('logout/', auth_view.LogoutView.as_view(),name = 'logout'),

    #회원가입
    #path('signup/',common_views.signup)

    path('signup/', common_views.signup_custom, name = 'signup'),
    #회원삭제
    path('delete/', common_views.delete, name = 'delete'),
    #회원수정
    path('update/', common_views.update, name = 'update'),

    #회원조회
    path('userinfo/', common_views.userinfo, name = 'userinfo'),

    
]

projects/myboard/myboard/urls.py
from django.contrib import admin
from django.urls import path, include

from board.views import home
urlpatterns = [
    path('', include('common.urls')),
    path("admin/", admin.site.urls),
    path('board/', include('board.urls')),
]

projects/myboard/board/models.py
from django.db import models
from django.utils import timezone #시간정보에 관한 모듈
from django.contrib.auth.models import User #auth_user 테이블과 매핑
# Create your models here.
class Board(models.Model):
    # 번호는 pk설정 안하면 장고가 자동으로  id 부여해줌

    ##필드와 필드사이에 컴마 금지###
    title = models.CharField(max_length=100)  #제목
    context = models.TextField(null = False, blank = False)  # 내용
    #writer = models.CharField(max_length = 10) #글쓴이
    input_date = models.DateTimeField(default = timezone.now) #작성일자
    view_count = models.IntegerField(default=0) #조회수

    #DB에는 필드이름 기본키(프라이머리) 이름으로 열이 생성됨    
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.id} ~~~ {self.title}'
        #return "{} : {}" .format(self.id, self.title)  <<<이렇게 써도 똑같음


#댓글정보를 포함하는 모델
class Reply(models.Model):
    #pk : 장고가 알아서 만들어줌(id)
    # 게시글번호(fk)
    board_obj = models.ForeignKey(Board, on_delete=models.CASCADE)
    # 사용자(fk)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # 댓글내용
    reply_content = models.TextField(null = False, blank = False)
    # 작성시간
    input_date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.reply_content

projects/myboard/common/models.py
from django.db import models

# Create your models here.

projects/myboard/common/forms.py
#forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

#UserCreationForm을 상속받는 UserForm을 작성
class UserForm(UserCreationForm):
    email=forms.EmailField(label = "이메일")
    first_name = forms.CharField
    last_name = forms.CharField
    
    

    class Meta: #폼의 정보를 담고 있는 내부 클래스
        model = User
        fields = ("username","email",'first_name','last_name')


class CustomChangeForm(UserChangeForm):
    
    class Meta:
        model = User
        fields = ("email","first_name","last_name")

projects/myboard/board/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect, JsonResponse

from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.core import serializers

from json import loads

from .models import Board, Reply
# Create your views here.

#게시판 목록보기
def index(request):
    print('index() 실행')
    board_list = Board.objects.all().order_by('-id')  #sql 에서는 DESC ASC 로 정렬 순서 정함
    context = {}

    if 'searchType' in request.GET and 'searchWord' in request.GET:
        search_type = request.GET['searchType']
        search_word = request.GET['searchWord']

        print("search_type: {}, search_word : {}".format(search_type, search_word))

        # match : java의 switch랑 비슷한
        match search_type:
            case 'title': #검색기준이 제목일때
                result = Board.objects.filter(title__contains = search_word)
            case 'writer': #검색기준이 글쓴이일때
                result = Board.objects.filter(writer__contains = search_word)
            case 'context' : #검색 기준이 내용일 때
                result = Board.objects.filter(context__contains = search_word)
        #검색을 했을때만 검색 기준과 키워드를 context에 넣는다

        context['searchWord'] = search_word
        context['searchType'] = search_type
    else : #QueryDict에 검색 조건과 키워드가 없을때
        result = Board.objects.all()

    result = result.order_by('-id')   

    #페이징 넣기
    #Paginator(목록,목록에 보여줄 개수)
    paginator = Paginator(result, 10)
    
    #paginator 클래스를 이용해서 자른 목록의 단위에서
    #몇번째 단위를 보여줄 것인지 정한다
    page_obj = paginator.get_page(request.GET.get('page'))
    
    
    # context['board_list'] = result
    #페이징한 일부 목록을 반환
    context['page_obj'] = page_obj

    return render(request, 'board/index.html', context)

def read(request,id):
    board = Board.objects.get(id = id)
    reply_list = Reply.objects.filter(board_obj = id).order_by('-id')
    board.view_count += 1
    board.save()
    context = {
        'board' : board,
        #'replyList' : reply_list
    }
    return render(request, 'board/read.html', context)

def home(request):
    return HttpResponseRedirect('/board/')

@login_required(login_url = 'common:login')
def write(request) :
    if request.method == 'GET':
        return render(request, 'board/board_form.html')
    else: #요청방식이 POST일때 할일
        title = request.POST['title']
       
        context = request.POST['context']
        author = request.user #요청에 들어있는 User 객체
        print(request.user)
        #현재 세션정보의 writer라는 키를 가진 데이터 취득
        # session_writer = request.session.get('writer')
        # if not session_writer: #세션의 정보가 없는 경우
        #     request.session['writer'] = request.POST['writer']
        # print(session_writer)

        # board = Board(
        #     title = title,
        #     wirter = writer,
        #     context = context
        # )
        # board.save() #db에 insert
        #객체.save
        Board.objects.create(
            title = title,
            author = author,
            context = context
        )
        return HttpResponseRedirect('/board/')
        #모델.objects.create(값)

@login_required(login_url = 'common:login')
def update(request, id):

    board = Board.objects.get(id = id)   ##데이터 출력
    if board.author.username != request.user.username:
        return HttpResponseRedirect('/board/')
    if request.method == "GET":
          #id로 찾은 친구 정보를 템플릿에 표시하기 위해서
          context = {'board': board}
          return render(request,'board/board_update.html', context)
    

    elif board.author.username == request.user.username:
          #id로 찾은 객체에 대해서 폼의 값으로 원래 객체의 값 덮어쓰기
          board.title = request.POST['title']
          
          board.context = request.POST['context']

          board.save()
    return HttpResponseRedirect('/board/')

@login_required(login_url = 'common:login')
def delete(request, id):
    print(id)
    #해당 객체를 가져와서 삭제
    board = Board.objects.get(id = id)

    #글 작성자의 id와 접속한 사람의 id가 같을때
    if board.author.username == request.user.username:
        board.delete()
    #다를 떄
    return HttpResponseRedirect('/board/')

    

def write_reply(request, id):
    print(request.POST)
    
    user = request.user
    reply_text = request.POST['replyText']

    # Reply.objects.create(
    #     user = user,
    #     reply_content = reply_text,
    #     board_obj = Board.objects.get(id = id)
    # )

    #queryset을 이용해 만들기
    board = Board.objects.get(id=id)
    board.reply_set.create(
        reply_content = reply_text,
        user = user
    )

    return HttpResponseRedirect('/board/'+str(id))

def delete_reply(request, id, rid):
    print(f'id: {id} rid: {rid}')

    Board.objects.get(id=id).reply_set.get(id=rid).delete()
    # response = (f'id: {id} rid: {rid}')
    #Reply.objects.get(id = rid).delete()
    return JsonResponse()
    

def update_reply(request,id):
    if request.method == 'GET':
        rid = request.GET['rid']
        board = Board.objects.get(id = id)
        context ={
            'update' : 'update',
            'board' : board, #id에 해당하는 Board 객체
            'reply' : board.reply_set.get(id = rid) #rid에 해당하는 Reply객체
        }
        return render(request, 'board/read.html', context)
    else:
        rid = request.POST['rid']

        reply = Board.objects.get(id=id).reply_set.get(id=rid)

        #폼에 들어있던 새로운 댓글 텍스트로 갱신
        reply.reply_content = request.POST['replyText']

        reply.save()
        
        return HttpResponseRedirect('/board/'+str(id))
        
        
def call_ajax(request):
    print("성공한것같읍니다?")
    print(request.POST)
    #JSON.stringify 하면 아래 표현은 사용 할 수 없음
    #print(request.POST['txt'])


    data = loads(request.body)
    print('템플릿에서 보낸 데이터',data)
    print(data['txt'])
    print(type(data))
    return JsonResponse({'result' : 'ㅊㅋㅊㅋ'})
    

def load_reply(request):

    id = request.POST['id']
    print(id)

    #해당하는 board id에 달려있는 모든 Reply가져오기

    #1번째 방법
    #Reply.objects.filter(board = id)

    #2번째 방법
    reply_list = Board.objects.get(id = id).reply_set.all()
    
    serialized_list = serializers.serialize("json", reply_list)

    response = {'response' : serialized_list}

    return JsonResponse(response)

projects/myboard/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
#장고가 제공하는 기본 회원가입 폼
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.decorators import login_required
#우리가 만든 커스텀 회원가입 폼
from .forms import UserForm
from .forms import CustomChangeForm
# Create your views here.
def index(request):
    #아까만든 common/indexhtml을 표시하고
    #loacalhost+8000/으로 들어갔을떄 잘표시되는지 확dls
    return render(request, 'common/index.html')

def signup(request):
    
    if request.method == 'POST':
        #요청객체가 담고있는 정보로 사용자 생성 폼 만든다
        print(request.POST)
        form = UserCreationForm(request.POST)

        if form.is_valid(): #form의 내용이 유효하다면\
            form.save() #db에 폼 정보 저장

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            #사용자인증
            user = authenticate(username = username, password = raw_password)
            #로그인
            login(request, user)
            return redirect('/')
    else:
        #GET방식으로 요청이 오면 비어있는 사용자 생성 폼 을 만든다
        form = UserCreationForm()
    return render(request, 'common/signup.html', {'form' : form})

def signup_custom(request):
    if request.method == 'POST':
        print(request.POST) # QueryDict 한번 보기

        #request.POST에 들어있는 정보를 UserForm 형식으로 변환
        form = UserForm(request.POST)

        #Form이 유효한가?
        if form.is_valid():
            form.save() #폼의 내용을 D B(auth_user)에 바로 저장 

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')

            #사용자 인증 후 로그인
            user = authenticate(username = username, password = raw_password)
            login(request, user)

            return redirect('/') #로그인하고 메인 페이지로 넘김
    else: #요청이 GET일때
        form = UserForm()

    return render(request, 'common/signup.html', {'form' : form})

def delete(request):
    if request.user.is_authenticated:
        request.user.delete() #유저 정보 삭제

        # render나 redirect의 파라미터로 app_name: url_name 작성가능
        return redirect('common:index')
    
def update(request):
    
    if request.method == 'POST':
        form = CustomChangeForm(request.POST,instance = request.user)
        if form.is_valid():
            form.save() #form이 유효하다면 해당 내용 저장
            return redirect('common:index')
    else:
        #CustomChangeForm(instace)보내면 django가 제공하는 기본 폼 사용 할 수 있음.
        form = CustomChangeForm()   

    return render(request, 'common/update.html', {'form' : form})


def userinfo(request):
    if request.method == 'GET':
        return render(request, 'common/userinfo.html')

projects/myboard/board/templates/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 틀이 되는 템플릿의 title 이 덮어써지지 않도록 -->
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
</head>
<body>

    <!-- 내가 집어 넣고 싶은 조각 (fragment)을 include -->
    {% include 'common/menubar.html' %}

    <!-- 다른 내용을 삽입할 자리를 만들기 -->
    {% block body %}{% endblock body %}
</body>
</html>

projects/myboard/board/templates/common/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        function confirmDelete(){
            if (confirm("정말로 삭제 하시겠읍니까?")) {
                return true;
            } else {
                return false;
            }
        }
        
    </script>
</head>
<body>
    <h1>안녕하세요</h1>
<!-- django에서 제공하는 User모델 -->
    <h2>hello1 
        {% if user.is_authenticated %}   <!--user 정보가 있으면 username 표시-->
        <span style="color: rgb(34, 0, 255); font-style: italic;" >
            {{user.username }}
        </span>님 반갑읍니다!
        {% else %}   <!--없으면 그냥 게스트 표시-->
        GUEST
        {% endif %}
    </h2>

    <ul>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'common:signup' %}">회원가입</a></li>
        <li><a href="{% url 'common:login' %}">로그인</a></li>
        {% elif user.is_authenticated %}
            <li><a href="{% url 'common:logout' %}"> 로그아웃</a></li>
            <li><a href="{% url 'common:delete' %}" onclick="return confirmDelete()"> 회원삭제</a></li>
            <li><a href="{% url 'common:userinfo' %}">회원정보조회</a></li>
        {% endif %}
        <li><a href="{% url 'board:index' %}"> 게시판으로 가기</a></li>
    </ul>
    
</body>
</html>

projects/myboard/board/templates/common/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
</head>
<body>
    <h2>로그인하기</h2>
    <form action="{% url 'common:login' %}" method="post">
        {% csrf_token %}
        <!-- 로그인성공후 이동할 url -->

        <!-- hidden태그 next의 value로 next를 사용하면 주소의 쿼리스트링에 있던 ?next=주소로 이동/ value로 특정 문자열을 사용하면 해당하는 주소로 이동 -->
        <input type="hidden" name="next" value="{{ next }}">
        <!-- 아이디와 비밀번호를 입력받는 폼 -->
        
        <table>
            <tr>
           <td> 아이디: <input type="text" name = "username"></td>
            </tr>
            <tr>
           <td>비밀번호: <input type="password" name = "password"></td>
            </tr>
        </table>
           <input type="submit" value="로그인">
        <!-- 로그인버튼 -->
        
    </form>
</body>
</html>

projects/myboard/board/templates/common/menubar.html
<!-- vs code 에서 . 입력하고 자동완성 하면  -->

<div>
    <a href="/">홈</a>&nbsp;&nbsp;
    {% if not user.is_authenticated %} 
    <a href="/signup">회원가입</a>&nbsp;&nbsp;
    <a href="/login">로그인</a>&nbsp;&nbsp;
    {% endif %} 
    {% if user.is_authenticated %}
    <a href="/logout">로그아웃</a>&nbsp;&nbsp;
    {% endif %}

    <!-- 아래의 호출법은 주소를 하드코딩하는게아니라 -->
    <!-- urls.py 에 정의된 name 속성을 통해서 이동 -->
    <a href="{% url 'board:index' %}">게시판으로 이동</a> //
    {% if user.is_authenticated %}
        {{user.username}} 님 반갑읍니다
        {% endif %}
</div>

projects/myboard/board/templates/common/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
</head>
<body>
    <h1>회원가입</h1>
    <form action="../signup/" method="post">
        {% csrf_token %}
        <!-- 각 폼에 적용한 name 속성은 UserCreationForm에서 제공하는 필드 이름과 같다. -->
        <table>
            <tr>
                <td>아 이 디 <input type="text" name="username"></td>
            </tr>
            <tr>
                <td>비밀번호 <input type="password" name="password1"></td>
            </tr>
            <tr>
                <td>비번확인 <input type="password" name="password2"></td>
            </tr>
            <tr>
                <td>E-메일 <input type="email" name="email"></td>
            </tr>
            <tr>
                <td>이름(성) <input type="text" name="last_name"></td>
            </tr>
            <tr>
                <td>이름(이름) <input type="text" name="first_name"></td>
            </tr>
        </table>
        <input type="submit" value="회원가입">
    </form>
</body>
</html>

projects/myboard/board/templates/common/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원정보 수정</title>
</head>
<body>
    
    <form action="{% url 'common:update' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <th>아이디</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>이름(성)</th>
                <td><input type="text" name="last_name" value="{{ user.last_name}}"></td>
            </tr>
            <tr>
                <th>이름</th>
                <td><input type="text" name="first_name" value="{{ user.first_name}}"></td>
            </tr>
            <tr>
                <th>이메일</th>
                <td><input type="text" name="email" value="{{ user.email }}"></td>
            </tr>
        </table>
        <input type="submit" value="수정">
    </form>
</body>
</html>

projects/myboard/board/templates/common/userinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
        function confirmDelete(){
            if (confirm("정말로 삭제 하시겠읍니까?")) {
                return true;
            } else {
                return false;
            }
        }
    </script>
    <title>회원정보보기</title>
</head>
<body>
    
    <form>
        {% csrf_token %}
        <table border="1">
            <tr>
                <th>아이디</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>이름(성)</th>
                <td>{{ user.last_name}}</td>
            </tr>
            <tr>
                <th>이름</th>
                <td>{{ user.first_name}}</td>
            </tr>
            <tr>
                <th>이메일</th>
                <td>{{ user.email }}</td>
            </tr>
        </table>
        <hr>
        <a href="{% url 'common:update' %}">회원정보수정</a>//
        <a href="{% url 'common:delete' %}" onclick="return confirmDelete()"> 회원삭제</a>
    </form>
</body>
</html>