projects/myboard/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:id>/', views.read, name = 'detail'),
    
    path('write/', views.write, name = 'write'),

    path('<int:id>/update/', views.update, name = 'update'),

    path('<int:id>/delete/', views.delete, name = 'delete'),

    path('<int:id>/write_reply/', views.write_reply, name= 'write_reply'),

    #댓글삭제주소
    path('<int:id>/delete_reply/<int:rid>/', views.delete_reply, name= 'delete_reply'),

    path('<int:id>/update_reply/', views.update_reply, name = 'update_reply'),

    #Ajax
    path('callAjax/', views.call_ajax),

    path('load_reply/', views.load_reply),
]

projects/myboard/myboard/urls.py
from django.contrib import admin
from django.urls import path, include

from board.views import home
urlpatterns = [
    path('', include('common.urls')),
    path("admin/", admin.site.urls),
    path('board/', include('board.urls')),
]

projects/myboard/board/models.py
from django.db import models
from django.utils import timezone #시간정보에 관한 모듈
from django.contrib.auth.models import User #auth_user 테이블과 매핑
# Create your models here.
class Board(models.Model):
    # 번호는 pk설정 안하면 장고가 자동으로  id 부여해줌

    ##필드와 필드사이에 컴마 금지###
    title = models.CharField(max_length=100)  #제목
    context = models.TextField(null = False, blank = False)  # 내용
    #writer = models.CharField(max_length = 10) #글쓴이
    input_date = models.DateTimeField(default = timezone.now) #작성일자
    view_count = models.IntegerField(default=0) #조회수

    #DB에는 필드이름 기본키(프라이머리) 이름으로 열이 생성됨    
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.id} ~~~ {self.title}'
        #return "{} : {}" .format(self.id, self.title)  <<<이렇게 써도 똑같음


#댓글정보를 포함하는 모델
class Reply(models.Model):
    #pk : 장고가 알아서 만들어줌(id)
    # 게시글번호(fk)
    board_obj = models.ForeignKey(Board, on_delete=models.CASCADE)
    # 사용자(fk)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # 댓글내용
    reply_content = models.TextField(null = False, blank = False)
    # 작성시간
    input_date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.reply_content

projects/myboard/board/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect, JsonResponse

from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.core import serializers

from json import loads

from .models import Board, Reply
# Create your views here.

#게시판 목록보기
def index(request):
    print('index() 실행')
    board_list = Board.objects.all().order_by('-id')  #sql 에서는 DESC ASC 로 정렬 순서 정함
    context = {}

    if 'searchType' in request.GET and 'searchWord' in request.GET:
        search_type = request.GET['searchType']
        search_word = request.GET['searchWord']

        print("search_type: {}, search_word : {}".format(search_type, search_word))

        # match : java의 switch랑 비슷한
        match search_type:
            case 'title': #검색기준이 제목일때
                result = Board.objects.filter(title__contains = search_word)
            case 'writer': #검색기준이 글쓴이일때
                result = Board.objects.filter(writer__contains = search_word)
            case 'context' : #검색 기준이 내용일 때
                result = Board.objects.filter(context__contains = search_word)
        #검색을 했을때만 검색 기준과 키워드를 context에 넣는다

        context['searchWord'] = search_word
        context['searchType'] = search_type
    else : #QueryDict에 검색 조건과 키워드가 없을때
        result = Board.objects.all()

    result = result.order_by('-id')   

    #페이징 넣기
    #Paginator(목록,목록에 보여줄 개수)
    paginator = Paginator(result, 10)
    
    #paginator 클래스를 이용해서 자른 목록의 단위에서
    #몇번째 단위를 보여줄 것인지 정한다
    page_obj = paginator.get_page(request.GET.get('page'))
    
    
    # context['board_list'] = result
    #페이징한 일부 목록을 반환
    context['page_obj'] = page_obj

    return render(request, 'board/index.html', context)

def read(request,id):
    board = Board.objects.get(id = id)
    reply_list = Reply.objects.filter(board_obj = id).order_by('-id')
    board.view_count += 1
    board.save()
    context = {
        'board' : board,
        #'replyList' : reply_list
    }
    return render(request, 'board/read.html', context)

def home(request):
    return HttpResponseRedirect('/board/')

@login_required(login_url = 'common:login')
def write(request) :
    if request.method == 'GET':
        return render(request, 'board/board_form.html')
    else: #요청방식이 POST일때 할일
        title = request.POST['title']
       
        context = request.POST['context']
        author = request.user #요청에 들어있는 User 객체
        print(request.user)
        #현재 세션정보의 writer라는 키를 가진 데이터 취득
        # session_writer = request.session.get('writer')
        # if not session_writer: #세션의 정보가 없는 경우
        #     request.session['writer'] = request.POST['writer']
        # print(session_writer)

        # board = Board(
        #     title = title,
        #     wirter = writer,
        #     context = context
        # )
        # board.save() #db에 insert
        #객체.save
        Board.objects.create(
            title = title,
            author = author,
            context = context
        )
        return HttpResponseRedirect('/board/')
        #모델.objects.create(값)

@login_required(login_url = 'common:login')
def update(request, id):

    board = Board.objects.get(id = id)   ##데이터 출력
    if board.author.username != request.user.username:
        return HttpResponseRedirect('/board/')
    if request.method == "GET":
          #id로 찾은 친구 정보를 템플릿에 표시하기 위해서
          context = {'board': board}
          return render(request,'board/board_update.html', context)
    

    elif board.author.username == request.user.username:
          #id로 찾은 객체에 대해서 폼의 값으로 원래 객체의 값 덮어쓰기
          board.title = request.POST['title']
          
          board.context = request.POST['context']

          board.save()
    return HttpResponseRedirect('/board/')

@login_required(login_url = 'common:login')
def delete(request, id):
    print(id)
    #해당 객체를 가져와서 삭제
    board = Board.objects.get(id = id)

    #글 작성자의 id와 접속한 사람의 id가 같을때
    if board.author.username == request.user.username:
        board.delete()
    #다를 떄
    return HttpResponseRedirect('/board/')

    

def write_reply(request, id):
    print(request.POST)
    
    user = request.user
    reply_text = request.POST['replyText']

    # Reply.objects.create(
    #     user = user,
    #     reply_content = reply_text,
    #     board_obj = Board.objects.get(id = id)
    # )

    #queryset을 이용해 만들기
    board = Board.objects.get(id=id)
    board.reply_set.create(
        reply_content = reply_text,
        user = user
    )

    return HttpResponseRedirect('/board/'+str(id))

def delete_reply(request, id, rid):
    print(f'id: {id} rid: {rid}')

    Board.objects.get(id=id).reply_set.get(id=rid).delete()
    # response = (f'id: {id} rid: {rid}')
    #Reply.objects.get(id = rid).delete()
    return JsonResponse()
    

def update_reply(request,id):
    if request.method == 'GET':
        rid = request.GET['rid']
        board = Board.objects.get(id = id)
        context ={
            'update' : 'update',
            'board' : board, #id에 해당하는 Board 객체
            'reply' : board.reply_set.get(id = rid) #rid에 해당하는 Reply객체
        }
        return render(request, 'board/read.html', context)
    else:
        rid = request.POST['rid']

        reply = Board.objects.get(id=id).reply_set.get(id=rid)

        #폼에 들어있던 새로운 댓글 텍스트로 갱신
        reply.reply_content = request.POST['replyText']

        reply.save()
        
        return HttpResponseRedirect('/board/'+str(id))
        
        
def call_ajax(request):
    print("성공한것같읍니다?")
    print(request.POST)
    #JSON.stringify 하면 아래 표현은 사용 할 수 없음
    #print(request.POST['txt'])


    data = loads(request.body)
    print('템플릿에서 보낸 데이터',data)
    print(data['txt'])
    print(type(data))
    return JsonResponse({'result' : 'ㅊㅋㅊㅋ'})
    

def load_reply(request):

    id = request.POST['id']
    print(id)

    #해당하는 board id에 달려있는 모든 Reply가져오기

    #1번째 방법
    #Reply.objects.filter(board = id)

    #2번째 방법
    reply_list = Board.objects.get(id = id).reply_set.all()
    
    serialized_list = serializers.serialize("json", reply_list)

    response = {'response' : serialized_list}

    return JsonResponse(response)

projects/myboard/board/templates/board/board_form.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    {% extends 'common/base.html' %}
    {% block title %}[글쓰기]{% endblock title %}
    {% block body %}
    <h1>[글쓰기]</h1>
    <form action="{%url 'board:write' %}" method="post">
        {% csrf_token %}
        <!-- 로그인 성공후 이동할 url -->
        <input type="hidden" name="next" value="/board/">
        <table>
            <tr>
                <th>제목</th>
                <td><input type="text" name="title"></td>
            </tr>
            <!-- {% if not request.session.writer %}
            <tr>
                <th>글쓴이</th>
                <td><input type="text" name="writer"></td>
            </tr>
            {% endif %} -->
            <tr>
                <th>내용</th>
                <td><textarea name="context" id="" cols="30" rows="10"></textarea></td>
            </tr>
            <tr>
                <th colspan = "2">
                    <input type="submit" value = "글쓰기">
                </th>
            </tr>
        </table>
    </form>

    {% endblock body %}

projects/myboard/board/templates/board/board_update.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    {% extends 'common/base.html' %}
    {% block title %}[글 수정하기]{% endblock title %}
    {% block body %}
    <h1 style="color: blue;">[글 수정하기]</h1>
    <form action="{% url 'board:update' board.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="/board/">
        <table>
            <tr>
                <th>제목</th>
                <td><input type="text" name="title" value="{{ board.title }}"></td>
            </tr>
            
            <!-- <tr>
                <th>글쓴이</th>
                <td><input type="text" name="writer" value="{{ board.writer }}"></td>
            </tr> -->
            
            <tr>
                <th>내용</th>
                <td><textarea name="context" id="" cols="30" rows="10" >{{ board.context }}</textarea></td>
            </tr>
            <tr>
                <th colspan = "2">
                    <input type="submit" value = "수정하기">
                </th>
            </tr>
        </table>
    </form>

    {% endblock body %}

projects/myboard/board/templates/board/index.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/base.css"> -->
    {# common/base.html을 상속받겠음 #}
    {% extends 'common/base.html' %}
    {% block title %}[게시판]{% endblock title %}

    {% block body %}
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function(){
            // alert("반갑읍니다~^_^");
        });
        function callFunction(){
            let data = { 'txt' : 'hello'};
            //AJAX로 서버와 통신을 할때에도 csrf토큰은 있어야 한다.
            $.ajax({
                url: '/board/callAjax/',
                type: 'post',
                headers: {'X-CSRFTOKEN': '{{csrf_token}}'},
                data: JSON.stringify(data), //js객체를 문자열화
                success: function(res){
                    console.log(res);
                    console.log(res.result); // res 객체에 들어있는 result라는 필드
                    console.log('성공했읍니다.');
                }
            })
        }
    </script>
    <h1>게시판</h1>
    {% if page_obj %}
      <table border="1">

        <tr>
            <th>글번호</th>
            <th>제목</th>
            <th>글쓴이</th>
            <th>날짜</th>
            <th>조회수</th>
        </tr>
    {% for board in page_obj %}
    <tr>
        <td>{{ board.id }}</td>
        <!-- 파라미터가 있는 주소를 호출할 떄 -->
        <td><a href="{% url 'board:detail' board.id %}">{{ board.title }}</a></td>
        <td>{{ board.author }}</td>
        <td>{{ board.input_date }}</td>
        <td style="text-align: center;">{{ board.view_count}}회  </td>
    </tr>
    {% endfor %}
    </table>
    {% else %}
    <table border="1">
            <tr>
                <th colspan="5">
                    게시글이 존재하지 않읍니다.
                </th>
            </tr>
    </table>
    {% endif %}
       
      
    </table>
    <!-- action을 비워놓게 되면 현재페이지의 주소를 다시 호출한다 -->
    <form action="">
        <select name="searchType" >
            {% if searchType == 'title' %}
                <option value="title" selected = "selected">제목</option>
            {% else%}
                <option value="title">제목</option>
            {% endif %}

            {% if searchType == 'writer' %}
                <option value="writer" selected = "selected">글쓴이</option>
            {% else%}
                <option value="writer">글쓴이</option>
            {% endif %}

            {% if searchType == 'context' %}
                <option value="context" selected = "selected">내용</option>
            {% else%}
                <option value="context">내용</option>
            {% endif %}
<!-- 
            <option value="title">제목</option>
            <option value="writer">글쓴이</option>
            <option value="context">내용</option> -->
        </select>
        <input type="text" name="searchWord" value = "{{searchWord}}">
        <input type="submit" value="검색">
    </form>
    <!-- 페이징 -->
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo;처음페이지로</a>
        <a href="?page={{ page_obj.previous_page_number }}">이전 페이지로</a>
    {% endif %}
    <!-- pagenator의 number 현재 페이지 번호 -->
    <!-- num_pagers 는 전체 페이지 수 -->
    page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number}}">다음페이지로</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">마지막 페이지로&raquo;</a>
    {% endif %}
    <br>
<!-- 페이징 2 : 가지고 있는 페이지의 번호 다 보여주기 -->
    {% for page_number in page_obj.paginator.page_range %}
    <a href="?page={{ page_number }}">{{ page_number }}</a>
         &nbsp;
    {% endfor %}
    <br>
<!-- 페이징3 : 2를 개선한 버전 -->
    {% for page_number in page_obj.paginator.page_range %}
    {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
        {% if searchWord %}
            <a href ="?page={{ page_number }}&searchType={{ searchType }}&searchWord={{ searchWord }}">{{ page_number }}</a>
            
        {% else %}
            <a href ="?page={{ page_number }}">{{page_number}}</a>
        {% endif %}
    {% endif %}
    {% endfor %}

    {% if user.is_authenticated %}
        
    <hr>
    <a href="{% url 'board:write' %}">글쓰기</a>
    {% endif %}
    <input type="button" value="눌러보세요" onclick="callFunction()"><br>
    <a href="http://127.0.0.1:8000/board/">첫 페이지로</a>
    


{% endblock body %}

projects/myboard/board/templates/board/read.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    {% extends 'common/base.html' %}
    {% block title %}게시글{% endblock title %}
    {% block body %}
    <!-- <form action="../../update_friend/{{ board.id }}/" method="get">
        {% csrf_token %}
        이름<input type="text" name="friend_name" value="{{ friend.friend_name }}"><br>
        나이<input type="text" name="friend_age" value="{{ friend.friend_age }}"><br>
        친구소개<textarea cols="50" rows="3" name="friend_bigo">{{ friend.friend_bigo }}</textarea><br>
        <input type="submit" value="수정">
    </form> -->
    
    <script>
      function confirmDelete(){
          if (confirm("정말로 삭제 하시겠읍니까?")) {
              return true;
          } else {
              return false;
          }
      }

      function showUpdateForm(param){
        // .../board/0/update_reply?rid=0
        location.href = 'update_reply?rid='+param;
      }
      $(document).ready(function(){
          loadReplyList();
      })
      function loadReplyList(){
        let bNum = '{{ board.id }}';
        
        console.log(bNum);
        $.ajax({
          url:'/board/load_reply/',
          type:'post',
          headers: {'X-CSRFTOKEN': '{{csrf_token}}'},
          data: {'id' : bNum },
          success: function(response){
            console.log(JSON.parse(response["response"]));

            let replyList = JSON.parse(response["response"])
            let str = "";
            $.each(replyList, function(i, item){
              let replyContent = item.fields.reply_content;
              // $("#replyList).append(replyContent + "<br>")");

            
              str += '<span style="color: rgb(0, 252, 17);">[댓글]: </span>' + replyContent + '&nbsp;&nbsp;&nbsp;';
              str += '<a href="#" onclick="showUpdateForm(' + item.pk + ')">수정 </a>';
              str += `<a href="#" onclick="delete_reply(` + item.pk + `)">/ 삭쫴</a>`;
              str += '<br>';
                
            }); 
            $("#replyList").html(str);
          }})}

                
  
      function delete_reply(rid){
        let bNum = '{{ board.id }}';
        alert(rid)
       
        $.ajax({
          url: '/board/' + bNum + '/delete_reply/' + rid + '/',
          type:'post',
          headers:{'X-CSRFTOKEN': '{{csrf_token}}'},
          success: function(response){
            console.log('댓글이 삭제되었읍니다 ^_^')
            loadReplyList();
          }
      })
    }
        
      // function update_reply(){
      //   let bNum = '{{ board.id }}'
      //   $.ajax({
      //     url:/update_reply/,
      //     type:'post',
      //     headers:{'X-CSRFTOKEN': '{{csrf_token}}'},
      //     data:{'id' : bNum },
      //     success:
      //   })
      // }
  </script>
        <table border="1">
        <tr>
            <th>글번호</th>
          <th>제목</th>
          <th>글쓴이</th>
          <th>날짜</th>
          <th>조회수</th>
        </tr>
        
          <tr>
            <td>{{ board.id }}</td>
            <td>{{ board.title }}</td>
            <td>{{ board.writer }}</td>
            <td>{{ board.input_date }}</td>
            <td style="text-align: center;">{{ board.view_count}}회 </td>
    
          </tr>
        
          <tr>
            <td colspan="5" style="text-align: center; font-weight: bold;" >게시글 내용</td>
          </tr>
          <tr>
            <td height="500" colspan="5" style="vertical-align: top;" >{{ board.context }}</td>
          </tr>
    </table>
    <!-- 수정 / 삭제 -->
    <!-- {{ board.author }}
    {{ user.username }} -->
    <!-- username 끼리 비교하려면 -->
    {% if board.author.username == user.username %}
    <a href="{% url 'board:update' board.id %}">수정</a>&nbsp;&nbsp;
    <a href="{% url 'board:delete' board.id %}"onclick="return confirmDelete()">삭제</a>
    {% endif %}

    <div id = "replyArea">
      <!-- 댓글 목록 표시할 곳 -->
      <div id = "replyList">
        <!-- board 객체 뿐만 아니라 board와 FK로 엮인 객체는 -->
        <!-- board.모델이름_set으로 가져올 수 있다 -->
        <!-- {% if board.reply_set %}
           {% for reply in board.reply_set.all %}
            <span style="color: rgb(0, 252, 17);">[댓글]: </span>{{ reply }}&nbsp;&nbsp;&nbsp;
            <a href="#" onclick="javascript:showUpdateForm('{{reply.id}}')">수정</a>
            <a href="{% url 'board:delete_reply' id=board.id rid=reply.id %}">삭제</a>
            <br>
          {% endfor %}
        {% else %}
          <p>등록된 댓글이 없읍니다.</p>
        {% endif %} -->
        <hr>
      </div>
      <!-- 댓글입력 폼 -->
      <!--context에 update에 대한 값을 찾지 못했을 때 -->
      <div id = "replyForm">
        
        {% if not update %}   
        <form action="{% url 'board:write_reply' board.id %}" method="post">
          {% csrf_token %}
          <textarea name="replyText" cols="30" rows="2"></textarea>
          <input type="submit" value="댓글쓰기">
        </form>
        {% else %}
        <form action="{% url 'board:update_reply' board.id %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="rid" value="{{reply.id}}">
          <textarea name="replyText" cols="30" rows="2">{{ reply.reply_content }}</textarea>
          <input type="submit" value="댓글수정">
        </form>
        {% endif %}
      </div>
    </div>
    <!-- board.author는 user하고 비교한다 -->
    <hr>
<a href="http://127.0.0.1:8000/board/">게시글 목록</a>
{% endblock body %}